name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDS }}'
        resource-group: 'ammohant'
        cluster-name: 'ammohant-2020'
        
    - run: cat $KUBECONFIG
    - run: 'kubectl get namespaces'
