name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDS }}'
        resource-group: 'shigupt-rg'
        cluster-name: 'shigupt'
        #arc-enabled: 'true'
        #aad-creds: '${{ secrets.AZURE_AADCREDS }}'
    - run: cat $KUBECONFIG
    - run: 'kubectl get nodes'
